# Dependencies
highlighter:      rouge
theme:            hyde

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            'PROGBITS'
tagline:          'Yet another OSS blog.'
description:      'Yet another OSS blog.'
url:              http://progbits.org
baseurl:          /

author:
  name:           'David Windsor'
  url:            http://progbits.org

markdown:         redcarpet
markdown_ext:     markdown,mkdown,mkdn,mkd,md
redcarpet:
    extensions: ["no_intra_emphasis", "tables", "autolink", "with_toc_data"]  

paginate:         5

# Custom vars
version:          1.2.0

github:
  repo:           https://github.com/dwindsor/dwindsor.github.io
