# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            '0x414.net'
tagline:          'Yet another security blog.'
description:      'Yet another security blog.'
url:              http://0x4141.net 
baseurl:          /

author:
  name:           'David Windsor'
  url:            http://0x4141.net

paginate:         5

# Custom vars
version:          1.2.0

github:
  repo:           https://github.com/dwindsor/dwindsor.github.io
