# Dependencies
highlighter:      pygments
theme: hyde

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            'PROGBITS'
tagline:          'Yet another OSS blog.'
description:      'Yet another OSS blog.'
url:              http://progbits.org
baseurl:          /

author:
  name:           'David Windsor'
  url:            http://progbits.org

paginate:         5

# Custom vars
version:          1.2.0

github:
  repo:           https://github.com/dwindsor/dwindsor.github.io
