# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            0x4141.net
tagline:          'Yet another security blog.'
description:      'Web log for security researcher and Linux hacker David Windsor.'
url:              http://0x4141.net
baseurl:          /

author:
  name:           'David Windsor'
  url:            http://0x4141.net

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/dwindsor/dwindsor.github.io
